# Generated by Django 3.0.5 on 2020-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
