# версия docker-compose
version: '2'

# имя директории для хранения данных
volumes:
  postgres_data:

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0
    # volume и связанная с ним директория в контейнере
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env